//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by generate-AllBusinessIcons-component.js.
//
//

import React from 'react'

/**
 * A list of all available icons in the icon set.
 */
export type IconDefinition = 'arrow-right' | 'close' | 'eye-slash' | 'eye' | 'home' | 'lock' | 'menu' | 'plus'

export const availableIcons: IconDefinition[] = [
  'arrow-right',
  'close',
  'eye-slash',
  'eye',
  'home',
  'lock',
  'menu',
  'plus',
]

export const IconSvg = {
  'arrow-right': (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 9 16">
      <path
        fill="#000"
        d="M2.092 15.998a1.14 1.14 0 01-.878-1.87l5.11-6.112-4.927-6.124a1.14 1.14 0 01.17-1.608 1.14 1.14 0 011.666.171L8.74 7.297a1.14 1.14 0 010 1.448l-5.702 6.842a1.14 1.14 0 01-.947.41z"
      />
    </svg>
  ),
  close: (
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-x" viewBox="0 0 16 16">
      <path d="M4.646 4.646a.5.5 0 01.708 0L8 7.293l2.646-2.647a.5.5 0 01.708.708L8.707 8l2.647 2.646a.5.5 0 01-.708.708L8 8.707l-2.646 2.647a.5.5 0 01-.708-.708L7.293 8 4.646 5.354a.5.5 0 010-.708z" />
    </svg>
  ),
  'eye-slash': (
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-eye-slash-fill" viewBox="0 0 16 16">
      <path d="M10.79 12.912l-1.614-1.615a3.5 3.5 0 01-4.474-4.474l-2.06-2.06C.938 6.278 0 8 0 8s3 5.5 8 5.5a7.029 7.029 0 002.79-.588zM5.21 3.088A7.028 7.028 0 018 2.5c5 0 8 5.5 8 5.5s-.939 1.721-2.641 3.238l-2.062-2.062a3.5 3.5 0 00-4.474-4.474L5.21 3.089z" />
      <path d="M5.525 7.646a2.5 2.5 0 002.829 2.829l-2.83-2.829zm4.95.708l-2.829-2.83a2.5 2.5 0 012.829 2.829zm3.171 6l-12-12 .708-.708 12 12-.708.708z" />
    </svg>
  ),
  eye: (
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-eye-fill" viewBox="0 0 16 16">
      <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z" />
      <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" />
    </svg>
  ),
  home: (
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-house-door-fill" viewBox="0 0 16 16">
      <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 00.5.5h4a.5.5 0 00.5-.5v-7a.5.5 0 00-.146-.354L13 5.793V2.5a.5.5 0 00-.5-.5h-1a.5.5 0 00-.5.5v1.293L8.354 1.146a.5.5 0 00-.708 0l-6 6A.5.5 0 001.5 7.5v7a.5.5 0 00.5.5h4a.5.5 0 00.5-.5z" />
    </svg>
  ),
  lock: (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 51 64">
      <path
        fill="#fff"
        d="M25.5 0C16.712 0 9.562 7.178 9.562 16v9.6H6.376C2.859 25.6 0 28.47 0 32v25.6C0 61.13 2.86 64 6.375 64h38.25C48.141 64 51 61.13 51 57.6V32c0-3.53-2.86-6.4-6.375-6.4h-3.188V16c0-8.822-7.15-16-15.937-16zm19.125 32l.006 25.6H6.375V32h38.25zm-28.688-6.4V16c0-5.293 4.29-9.6 9.563-9.6 5.272 0 9.563 4.307 9.563 9.6v9.6H15.936z"
      />
    </svg>
  ),
  menu: (
    <svg xmlns="http://www.w3.org/2000/svg" className="bi bi-list" viewBox="0 0 16 16">
      <path d="M2.5 12a.5.5 0 01.5-.5h10a.5.5 0 010 1H3a.5.5 0 01-.5-.5zm0-4a.5.5 0 01.5-.5h10a.5.5 0 010 1H3a.5.5 0 01-.5-.5zm0-4a.5.5 0 01.5-.5h10a.5.5 0 010 1H3a.5.5 0 01-.5-.5z" />
    </svg>
  ),
  plus: (
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-plus" viewBox="0 0 16 16">
      <path d="M8 4a.5.5 0 01.5.5v3h3a.5.5 0 010 1h-3v3a.5.5 0 01-1 0v-3h-3a.5.5 0 010-1h3v-3A.5.5 0 018 4z" />
    </svg>
  ),
}
